name: SCimilarity
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.11.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py310h7c4b9e2_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - brotli-python=1.2.0=py310h8cfb67f_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cffi=2.0.0=py310he7384ee_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310hff52083_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lark=1.3.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.1.4=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.5.0=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parallel=20170422=pl5.22.0_0
  - parso=0.8.5=pyhcf101f3_0
  - perl=5.22.0.1=0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psutil=7.1.3=py310h139afa4_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - pyzmq=27.1.0=py310h4f33d48_0
  - readline=8.2=h8c095d6_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.5.0=pyhcf101f3_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.2=py310h7c4b9e2_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py310h139afa4_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anndata==0.11.4
      - annoy==1.17.3
      - antlr4-python3-runtime==4.9.3
      - array-api-compat==1.12.0
      - asciitree==0.3.3
      - async-timeout==5.0.1
      - biocframe==0.6.3
      - biocutils==0.2.3
      - captum==0.8.0
      - cellarr==0.6.1
      - certifi==2025.10.5
      - circlify==0.15.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.2.1
      - fasteners==0.20
      - filelock==3.20.0
      - fire==0.7.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - genomicranges==0.7.3
      - h5py==3.15.1
      - hnswlib==0.8.0
      - imageio==2.37.2
      - iniconfig==2.3.0
      - iranges==0.5.4
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - legacy-api-wrap==1.5
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - matplotlib==3.10.7
      - mopsy==0.3.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - natsort==8.4.0
      - networkx==3.4.2
      - numba==0.62.1
      - numcodecs==0.13.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - obonet==1.1.1
      - omegaconf==2.3.0
      - pandas==2.3.3
      - patsy==1.0.2
      - pillow==12.0.0
      - pluggy==1.6.0
      - propcache==0.4.1
      - pyarrow==22.0.0
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pytest==9.0.1
      - pytorch-lightning==2.5.6
      - rpds-py==0.28.0
      - scanpy==1.11.5
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scimilarity==0.4.1
      - scipy==1.15.3
      - scrublet==0.2.3
      - seaborn==0.13.2
      - session-info2==0.2.3
      - statsmodels==0.14.5
      - summarizedexperiment==0.5.5
      - sympy==1.14.0
      - tblib==3.2.1
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiledb==0.35.2
      - tiledb-cloud==0.14.3
      - tiledb-vector-search==0.15.0
      - torch==2.9.0
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - triton==3.5.0
      - umap-learn==0.5.9.post2
      - yarl==1.22.0
      - zarr==2.18.3
prefix: /gpfs/flash/home/yr/miniconda3/envs/SCimilarity
